main: com.njdaeger.enhanceddebugstick.griefprevention.GP_Impl
name: EnhancedDebugStick-GriefPrevention
version: ${project.version}
api-version: 1.13
author: NJDaeger
depend:
  - EnhancedDebugStick
  - GriefPrevention